"""Initial migration

Revision ID: f4e16d3fbe12
Revises: 
Create Date: 2026-01-24 22:15:55.869157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4e16d3fbe12'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alert_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('min_confidence', sa.Float(), nullable=True),
    sa.Column('in_app_alerts', sa.Boolean(), nullable=True),
    sa.Column('email_alerts', sa.Boolean(), nullable=True),
    sa.Column('push_notifications', sa.Boolean(), nullable=True),
    sa.Column('show_pattern_alerts', sa.Boolean(), nullable=True),
    sa.Column('show_behavioral_alerts', sa.Boolean(), nullable=True),
    sa.Column('show_time_based_alerts', sa.Boolean(), nullable=True),
    sa.Column('show_market_alerts', sa.Boolean(), nullable=True),
    sa.Column('real_time_alerts', sa.Boolean(), nullable=True),
    sa.Column('daily_summary', sa.Boolean(), nullable=True),
    sa.Column('weekly_report', sa.Boolean(), nullable=True),
    sa.Column('default_snooze_hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('risk_results', sa.JSON(), nullable=True),
    sa.Column('score_result', sa.JSON(), nullable=True),
    sa.Column('ai_explanations', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deriv_connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('api_token_encrypted', sa.Text(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('connection_name', sa.String(), nullable=True),
    sa.Column('connection_status', sa.String(), nullable=True),
    sa.Column('last_sync_status', sa.String(), nullable=True),
    sa.Column('account_info', sa.JSON(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('auto_sync', sa.Boolean(), nullable=True),
    sa.Column('sync_frequency', sa.String(), nullable=True),
    sa.Column('sync_days_back', sa.Integer(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_successful_sync', sa.DateTime(), nullable=True),
    sa.Column('total_syncs', sa.Integer(), nullable=True),
    sa.Column('total_trades_synced', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('disabled_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('max_position_size_pct', sa.Float(), nullable=True),
    sa.Column('min_win_rate', sa.Float(), nullable=True),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=True),
    sa.Column('min_rr_ratio', sa.Float(), nullable=True),
    sa.Column('min_sl_usage_rate', sa.Float(), nullable=True),
    sa.Column('ai_enabled', sa.Boolean(), nullable=True),
    sa.Column('preferred_model', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('deriv_trades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('deriv_trade_id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('contract_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('contract_type', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('buy_price', sa.Float(), nullable=False),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('barrier', sa.Float(), nullable=True),
    sa.Column('barrier2', sa.Float(), nullable=True),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('payout', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('purchase_time', sa.DateTime(), nullable=False),
    sa.Column('expiry_time', sa.DateTime(), nullable=True),
    sa.Column('sell_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('exit_spot', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['deriv_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deriv_trades_deriv_trade_id'), 'deriv_trades', ['deriv_trade_id'], unique=False)
    op.create_index(op.f('ix_deriv_trades_transaction_id'), 'deriv_trades', ['transaction_id'], unique=False)
    op.create_table('predictive_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('prediction_data', sa.JSON(), nullable=True),
    sa.Column('trigger_conditions', sa.JSON(), nullable=True),
    sa.Column('suggested_actions', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('snoozed_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('sync_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('trades_fetched', sa.Integer(), nullable=True),
    sa.Column('trades_new', sa.Integer(), nullable=True),
    sa.Column('trades_updated', sa.Integer(), nullable=True),
    sa.Column('trades_skipped', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('logs', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['deriv_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_source', sa.String(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('trade_id', sa.String(), nullable=True),
    sa.Column('analysis_triggered', sa.Boolean(), nullable=True),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['deriv_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('action_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['predictive_alerts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_history')
    op.drop_table('webhook_events')
    op.drop_table('sync_logs')
    op.drop_table('reports')
    op.drop_table('predictive_alerts')
    op.drop_index(op.f('ix_deriv_trades_transaction_id'), table_name='deriv_trades')
    op.drop_index(op.f('ix_deriv_trades_deriv_trade_id'), table_name='deriv_trades')
    op.drop_table('deriv_trades')
    op.drop_table('user_settings')
    op.drop_table('deriv_connections')
    op.drop_table('analyses')
    op.drop_table('alert_settings')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
